use_frameworks!

platform :ios, '9.0'

target 'Define_Example' do
 pod 'Define', :git => 'https://github.com/MasterYong/Define.git'

  target 'Define_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
